CONTRIBUTING.md
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
=> CONTRIBUTING.md -> CLA -> DCO

go.mod, pkg/jobmanager/bundles.go, pkg/pluginregistry/bundles.go, pkg/runner/test_runner_test.go, plugins/teststeps/s3fileupload/s3fileupload.go, plugins/teststeps/waitport/waitport.go, plugins/teststeps/waitport/waitport_test.go
These are the missing ones that we had in the old repo since the fork happened
https://github.com/facebookincubator/contest/pull/298
https://github.com/facebookincubator/contest/pull/300
https://github.com/facebookincubator/contest/pull/301
=> merge missing PRs from facebookincubator/contest

plugins/teststeps/exec/transport/ssh_process.go, tests/integ/plugins/exec_plugin_test.go
- as a side-effect of the workaround with allocating a pty so that
the remote process gets killed on context cancellation, it resulted
in the stdout and stderr of the remote process being combined and
seen as stdout by the exec transport
- refactor back to using ssh signals to kill the remote process, but
since that isn't always implemented in the ssh server, just try to
signal and abandon the remote process after a timeout
- added a TODO in case a better fix for this is available in the future
- testing: this is covered by TestExecPluginSSHTimeout and TestExecPluginSSHCancel integ tests
=> Fix exec ssh process mixing stdout and stderr

pkg/runner/test_runner_test.go
=> Refactor TestRunner unit tests: use test suite

pkg/runner/test_runner.go
When running tests I noticed:
==================
WARNING: DATA RACE
Write at 0x00c000255348 by goroutine 95:
github.com/linuxboot/contest/pkg/runner.(*TestRunner).checkStepRunnersLocked()
/go/src/github.com/linuxboot/contest/pkg/runner/test_runner.go:737 +0x277
github.com/linuxboot/contest/pkg/runner.(*TestRunner).runMonitor()
/go/src/github.com/linuxboot/contest/pkg/runner/test_runner.go:788 +0x5ae
github.com/linuxboot/contest/pkg/runner.(*TestRunner).run()
/go/src/github.com/linuxboot/contest/pkg/runner/test_runner.go:226 +0xce4
github.com/linuxboot/contest/pkg/runner.(*TestRunner).Run()
/go/src/github.com/linuxboot/contest/pkg/runner/test_runner.go:134 +0x613
github.com/linuxboot/contest/pkg/runner.(*JobRunner).runTest()
/go/src/github.com/linuxboot/contest/pkg/runner/job_runner.go:378 …
=> Fix target result channel close race condition

pkg/runner/job_runner.go, pkg/runner/job_runner_test.go, pkg/runner/test_runner.go, pkg/runner/test_runner_test.go, tests/integ/plugins/cmd_plugin_test.go, tests/integ/plugins/exec_plugin_test.go, tests/integ/plugins/testrunner_test.go
Fix: https://github.com/linuxboot/contest/issues/40
=> Refactor TestRunner: move jobID/runID/testAttempt from TestRunner

pkg/jobmanager/jobmanager.go
Pause jobs in "checkIdle loop" if ctx is paused
=> Fix race condition in JobManager.Run

pkg/runner/base_test_suite_test.go, pkg/runner/job_runner.go, pkg/runner/job_runner_test.go, pkg/runner/job_status.go, pkg/target/target.go, pkg/target/target_test.go
https://github.com/linuxboot/contest/issues/77
=> Retry test if targets acquiring failed

pkg/target/target.go, pkg/target/target_test.go
Tolerate "null" bytes unmarshalling in UnmarshalErrPayload
=> Tolerate "null" bytes unmarshalling in UnmarshalErrPayload

pkg/runner/step_runner.go, pkg/runner/test_runner.go
Should fix: https://github.com/linuxboot/contest/issues/71
=> Move detection of lost targets from TestRunner to StepRunner

pkg/api/listener.go, pkg/jobmanager/jobmanager.go, plugins/listeners/httplistener/httplistener.go, tests/integ/jobmanager/common.go
In this PR, I removed the registry parameter from the listener interface
=> Remove the prometheus registry parameter

pkg/runner/job_runner.go
log number of acquired targets for better debugging
=> Log number of acquired targets

cmds/admin_server/main.go, cmds/admin_server/server/server.go, cmds/admin_server/storage/mongo/mongo.go, cmds/admin_server/storage/storage.go
=> Add context to storage api

cmds/admin_server/server/server.go, cmds/admin_server/storage/mongo/mongo.go
- store logger in route handler
- pass logger to storage via xcontext
=> Use proper logging in admin server

cmds/admin_server/.gitignore, cmds/admin_server/server/server.go, cmds/admin_server/ui/package-lock.json, cmds/admin_server/ui/package.json, cmds/admin_server/ui/public/index.html, cmds/admin_server/ui/src/app.tsx, cmds/admin_server/ui/src/index.tsx, cmds/admin_server/ui/styles/app.scss, cmds/admin_server/ui/tsconfig.json, cmds/admin_server/ui/webpack.config.js, go.mod, go.sum
- configure webpack & dev server
- configure typescript for react
=> Init frontend infrastructer

pkg/loggerhook/httphook.go, tests/integ/admin_server/logendpoint_test.go
- logs sent via http should be server Logs
=> Use server log for submitting logs

cmds/admin_server/server/server.go, cmds/admin_server/storage/mongo/mongo.go, cmds/admin_server/storage/storage.go, tests/integ/admin_server/getlogs_test.go
jobID must be added to query in order to be used in filtering entries in the database
=> Add job ID to query struct

pkg/runner/step_state.go, pkg/runner/test_runner.go
TestRunner and StepState were highly coupled that prevents further refactoring: https://github.com/linuxboot/contest/issues/97
StepState continues to be
The next step: make targetHandler decide when to stop test step (when no more targets are expected).
=> Make TestRunner's StepState an independent entity

cmds/admin_server/main.go, cmds/admin_server/server/server.go
- add tls flags to serve over https
- add middlewares parameter to support authentication and other middlewares
- testing 
- I generated a localhost cert using `mkcert` and tested setting the tlsCert & tlsKey flags
=> Add tls and middlewares parameter

cmds/admin_server/storage/mongo/mongo.go, cmds/admin_server/storage/storage.go
- remove `Close` from storage api
=> Refactor admin server storage api

pkg/runner/step_state.go
Found in unit test:
time="2022-08-21T19:35:18Z" level=debug msg="[Target{ID: \"T1\"} 0 init <nil>]: target handler active" file="test_runner.go:351" target=T1
time="2022-08-21T19:35:18Z" level=debug msg="[Target{ID: \"T1\"} 0 begin <nil>]: injecting into [#0 Step1]" file="test_runner.go:392" target=T1
time="2022-08-21T19:35:18Z" level=error msg="err: test step Step1 paniced, trace: \"panic step / goroutine 2664 [running]:\\nruntime/debug.Stack(0xc000012948, 0xe4d620, 0x1085100)\\n\\t/usr/local/go/src/runtime/debug/stack.go:24 +0xab\\ngithub.com/linuxboot/contest/pkg/runner.(*StepRunner).runningLoop.func2.1(0xc0004d0080, 0x10aac58, 0xc000580be0, 0x109d950, 0x17089b8, 0xf45ded, 0x5, 0x0, 0xc00028fa10)\\n\\t/go/src/github.com/linuxboot/contest/pkg/runner/step_runner.go:395 …
=> Fix race condition in step runner's run error propagation

run_lint.sh
=> Increase the linter timeout

pkg/test/param_expander.go, pkg/test/param_expander_test.go
- add ptr, interface, map, array
- fix typo in slice branch
- unit tests
Signed-off-by: mimir-d <mimir-d@users.noreply.github.com>
=> [pkg/test] add more needed type handling to ParamExpander

pkg/runner/test_runner.go, pkg/runner/test_runner_test.go
- design change: previously the plugins Run() methods would be called when any one target reached said step; now all the pipeline step plugins are started right at the beginning
- there is no downside, the initial optimization was for memory usage, however there would be a point at the end of the run when all plugins had been started, therefore the maximal memory usage is still reached
- the reasoning for starting all plugins is to allow them to get (and save) any initialization time data gatherings (eg. from ctx, but other sources as well). This state will be saved and properly resumed later, a point when that initialization data may no longer be available, but was in the originally started test/run.
Signed-off-by: mimir-d <mimir-d@users.noreply.github.com>
=> start all pipeline plugins before any processing

go.mod, go.sum, plugins/teststeps/qemu/README.md, plugins/teststeps/qemu/qemu.go
Makes it possible to test and interact with firmware/
OS images in qemu.
For more information on how to use the plugin:
plugins/teststeps/qemu/README.md
Signed-off-by: Jo <johannes.bartunek@9elements.com>
=> plugins/teststeps/qemu.go: Add qemu teststep.
