linuxboot/contest

pkg/jobmanager/job.go
pkg/jobmanager/job_test.go
pkg/test/test.go

All testing frameworks have an ability to disable tests.
For that purpose, a TestDescriptor.Disabled field was added

Disable TestDescriptor via "Disabled" property

---

docker/contest/tests.sh
pkg/event/testevent/test.go
pkg/job/events.go
pkg/jobmanager/job.go
pkg/runner/job_runner.go
pkg/runner/job_runner_test.go
pkg/runner/job_status.go
pkg/runner/test_runner.go
pkg/runner/test_runner_test.go
pkg/test/test.go
tests/e2e/e2e_test.go
tests/e2e/test-retry.yaml
tests/integ/jobmanager/common.go
tests/integ/plugins/cmd_plugin_test.go
tests/integ/plugins/exec_plugin_test.go
tests/integ/plugins/testrunner_test.go

Initial implementation of test retry (similar to previous implementation of step retry).
Test retry is useful when target became broken and we should re-launch test from the beginning.
Next PR: add test retry to database.

Feature test retry

---

pkg/event/frameworkevent/framework.go
pkg/jobmanager/resume.go
pkg/jobmanager/status.go
plugins/storage/rdbms/events.go

Because ID is a new field, we are breaking contracts (a bit)

Order framework events by ID in jobmanager status/resume methods

---

pkg/event/frameworkevent/framework.go
pkg/event/testevent/test.go
pkg/jobmanager/resume.go
pkg/jobmanager/status.go
plugins/storage/memory/memory.go
plugins/storage/memory/memory_test.go
plugins/storage/rdbms/events.go

Initial problem
We had a bug in Status() method of a JobManager that didn't do the ordering of events obtained from the storage, assuming that the last extracted event is the latest one.
We had a discussion and came to conclusion that the best approach of solving this problem is to ask Storage for an explicit monotonic SequenceID support (inside a single Job) for each events.
The client code of the Storage should use SequenceIDs to do the ordering between events.

Implement ordering of Events by using sequential IDs

---

pkg/xcontext/logger/logadapter/logrus/fix_caller_hook.go

In our internal building system there is an additional prefix for outside code. Which 
```
[2021-12-09T06:21:56.019-08:00 D minimal_logger.go:39] my trace ID is 029ed5eb-f2b7-442f-91d2-65002285b0cb
[2021-12-09T06:21:56.020-08:00 I minimal_logger.go:39] Registering target manager provtest
[2021-12-09T06:21:56.020-08:00 I minimal_logger.go:39] Registering target manager serf
[2021-12-09T06:21:56.020-08:00 I minimal_logger.go:39] Registering target manager vmleasing
[2021-12-09T06:21:56.020-08:00 I minimal_logger.go:39] Registering target manager targetlist
```
```
[2021-12-09T06:24:05.440-08:00 D main.go:176] my trace ID is 0ad3a6a6-5312-4977-a95a-cb2864e93b56
[2021-12-09T06:24:05.440-08:00 I pluginregistry.go:63] Registering target manager basset2
[2021-12-09T06:24:05.441-08:00 I …
```

fix(xcontext): Fix caller file detection in logrus

---

pkg/runner/base_test_suite_test.go
pkg/runner/job_runner_test.go
pkg/runner/step_runner_test.go
pkg/runner/test_runner_test.go

Move global variable ctx into suite
Use BaseTestSuite in TestRunner tests

Improve BaseTestSuite

---

pkg/runner/step_runner.go
pkg/runner/step_runner_test.go
pkg/runner/test_runner.go

Check for ErrTestStepReturnedUnexpectedResult in StepRunner
Fixes:
https://github.com/linuxboot/contest/issues/60
https://github.com/linuxboot/contest/issues/61
https://github.com/linuxboot/contest/issues/66

Move emission of EventTargetIn/EventTargetOut/EventTargetErr to StepRunner

---

plugins/teststeps/echo/echo.go

This plugin is useful to quickly test new user functions (for templates), but it would need to actually run templates for that.
While I was here, I found the number of arguments in the output is wrong, it will always contain a MISSING.
Signed-off-by: Tobias Fleig <tfleig@fb.com>

plugins/echo: Expand text parameter and fix number of output vars

---

pkg/runner/test_runner.go

When a Paused signal was received, TestRunner cancelled step's context which could prevent correct results processing.
Partially restored logic in runMonitor removed in https://github.com/linuxboot/contest/commit/d952dfa563c451cfbfd31a0ab2eaffd04856064f# 
Fixing: https://github.com/linuxboot/contest/issues/86

Fix on pause race condition in TestRunner

---

cmds/clients/contestcli/cli/cli.go
cmds/clients/contestcli/cli/verbs.go
pkg/config/jobdescriptor.go
pkg/job/job.go
pkg/job/job_test.go
pkg/jobmanager/start.go
tests/integ/jobmanager/jobdescriptors.go
tests/integ/migration/common.go

In this merge request, I added the version field to the job descriptor , so that the server can check that it runs jobs that can understand. The check is done before the start of the job by calling `CheckVersion` on the job descriptor. This resolves #20.

Add versioning to json test descriptor

---

pkg/xcontext/context.go

TraceID is random and therefore has an unlimited number of possible values. Which makes it unusable for metrics. Therefore it should be a Field and not a Tag.

fix(xcontext): TraceID is a Field, not a Tag

---

docker/mysql/Dockerfile
pkg/api/api.go

make "api_method" a field in order not to miss the metric counters

fix(xcontext): api_method should be a Field

---

pkg/xcontext/metrics/prometheus/metrics.go
pkg/xcontext/metrics/prometheus/metrics_test.go
pkg/xcontext/metrics/prometheus/option.go

This is require due to 3 reasons:
* Prometheus does not really support deleting metrics. But in our design we need to dynamically update the possible collection of labels. So we do some unsafe hackery to make that possible. And to disable this behavior one may want to just disable labels.
* Prometheus does not have garbage collection for label values which were not used for a long time. Once a value is used it stays forever without manual intervention. Which creates a memory consumption problem in some applications.
* Somebody may just want to have flat metrics due to reasons not related to prometheus.

feat(xcontext): Allow to disable labels in the prometheus adapter

---

cmds/admin_server/main.go
cmds/admin_server/server/server.go
cmds/admin_server/storage/mongo/mongo.go
cmds/admin_server/storage/storage.go
tests/integ/admin_server/flags_test.go
tests/integ/admin_server/getlogs_test.go
tests/integ/admin_server/logendpoint_test.go

- add GET `log` endpoint to query logs
- support text search, date and log level filtering
- add integ test for the log query endpoint

Add log query endpoint

---

pkg/runner/step_runner.go
pkg/runner/step_runner_test.go
pkg/runner/test_runner.go

Previously StepRunner reported target results (and self) via channel that aligned with previous code (we stand for small step changes), but was awful in general as it required non-trivial passing results to state machine.
I refactored code such that  AddTargetToStep returns a waitable object that can report result for the added target.
That removed all code regarding to that results passing.
Fixes: https://github.com/linuxboot/contest/issues/74, https://github.com/linuxboot/contest/issues/54
Note:
targetStepPhaseResultPending is now not needed. I kept it for compatibility (iota). In practice it was impossible to get in resume state and has not code for proper restoration, so we face no risk for a breaking change for some paused state.
The ugly test_runner.go became 100 LoCs shorter.
Next …

StepRunner: return ResultNotifier in AddTargetToStep function

---

cmds/contest/server/server.go

admin server addr flag  should be `""` by default.

Fix adminServerAddr flag usage

---

cmds/contest-generator/core-plugins.yml
cmds/contest/main.go
plugins/teststeps/gathercmd/gathercmd.go

- this is a gather type plugin, holds onto all targets and runs the
given command once; returns a framework error if the command fails
- add to contest generator and server
testing:
- server with resume
```
> go run . --adminServerAddr "" --resumeJobs --pauseTimeout 10s
[...]
[2022-07-28T22:15:10.605+01:00 D localsetup.go:176] Running command: /usr/bin/sleep 60m attempt=%!s(uint32=0)   job_id=11       run_id=1        step_index=0  step_label=setup
```
- contestcli
```
> go run . start -w < ./descriptors/start-literal.json
```
with
```
"Steps": [
{
"name": "localsetup",
"label": "setup",
"parameters": {
"binary": [
"sleep"
],
"args": [
"60m"
]
}
}
]
```
Also tested successful setup, failing setup, canceled while running command.

Add localsetup test step

---

cmds/admin_server/server/server.go
cmds/admin_server/storage/mongo/mongo.go
cmds/admin_server/storage/storage.go
tests/integ/admin_server/getlogs_test.go
tests/integ/admin_server/logendpoint_test.go

- separate storage entities from server entities
- use proper struct tags

refactor admin server desing

---

cmds/admin_server/storage/mongo/mongo.go
tests/integ/admin_server/getlogs_test.go

get endpoint test file should use the proper "server/storage" entities to parse the logs from the "server response/db query".
- use server and mongostroage log struct in the integ testing

Use proper entities when test GET endpoint

---

pkg/runner/step_state.go
pkg/runner/test_runner.go

The test logs are:
time="2022-08-07T18:51:48Z" level=debug msg="monitor: active" file="test_runner.go:447"
time="2022-08-07T18:51:48Z" level=debug msg="monitor: starting at step [#0 Step1]" file="test_runner.go:449"
time="2022-08-07T18:51:48Z" level=debug msg="monitor pass 1: current step [#0 Step1]" file="test_runner.go:462"
time="2022-08-07T18:51:48Z" level=debug msg="monitor pass 1: [#0 Step1]: [Target{ID: \"TExtra\"} 0 init false <nil>]" file="test_runner.go:466"
time="2022-08-07T18:51:48Z" level=debug msg="monitor pass 1: [#0 Step1]: not all targets injected yet ([Target{ID: \"TExtra\"} 0 init false <nil>])" file="test_runner.go:471"
time="2022-08-07T18:51:48Z" level=debug msg="[Target{ID: \"TExtra\"} 0 init false <nil>]: target handler active" file="test_runner.go:326" target=TExtra …

Fix the case when step generates an error which is passed to a step state, but test runner exits first

---

pkg/test/functions.go
pkg/test/param_expander.go
pkg/test/parameter.go
pkg/test/parameter_test.go
pkg/test/step.go
plugins/teststeps/cmd/cmd.go
plugins/teststeps/cpucmd/cpucmd.go
plugins/teststeps/echo/echo.go
plugins/teststeps/exec/exec.go
plugins/teststeps/exec/runner.go
plugins/teststeps/gathercmd/gathercmd.go
plugins/teststeps/s3fileupload/s3fileupload.go
plugins/teststeps/sshcmd/sshcmd.go
plugins/teststeps/waitport/waitport.go

Minimal change to make step variables feature fully work in prod

Parameter.Expand consumes optional StepsVariables argument

---

pkg/runner/step_runner.go

The reason was the following test failure:
time="2022-08-09T15:09:51Z" level=debug msg="monitor: active" file="test_runner.go:447"
time="2022-08-09T15:09:51Z" level=debug msg="monitor: starting at step [#0 Step1]" file="test_runner.go:449"
time="2022-08-09T15:09:51Z" level=debug msg="monitor pass 1: current step [#0 Step1]" file="test_runner.go:462"
time="2022-08-09T15:09:51Z" level=debug msg="monitor pass 1: [#0 Step1]: [Target{ID: \"T1\"} 0 init false <nil>]" file="test_runner.go:466"
time="2022-08-09T15:09:51Z" level=debug msg="monitor pass 1: [#0 Step1]: not all targets injected yet ([Target{ID: \"T1\"} 0 init false <nil>])" file="test_runner.go:471"
time="2022-08-09T15:09:51Z" level=debug msg="[Target{ID: \"T1\"} 0 init false <nil>]: target handler active" file="test_runner.go:326" …

Always wait for StepRunner to finish in WaitResults method even in case of a failure

---

cmds/admin_server/server/server.go
cmds/admin_server/storage/mongo/mongo.go
cmds/admin_server/storage/storage.go
pkg/loggerhook/httphook.go
tests/integ/admin_server/logendpoint_test.go

Use batch logic to push logs

---

pkg/runner/step_state.go
pkg/runner/test_runner.go

Fixes https://github.com/linuxboot/contest/issues/62

TestRunner: Remove step stopping loop in RunMonitor

---

cmds/contest/server/server.go
pkg/loggerhook/httphook.go
pkg/xcontext/bundles/logrusctx/new_context.go
pkg/xcontext/bundles/options.go

- Add options to override http logger defaults from the cli
- resolve #130 

Add http config options

---

tests/common/goroutine_leak_check/goroutine_leak_check.go
tests/common/goroutine_leak_check/goroutine_leak_check_test.go

Make multiple iterations checks to reduce sleep time in case no goroutines leaked

Refactor goroutine leaks checker

---

cmds/admin_server/server/server.go

storage errors should be logged, so that we can trace problems better

Log storage errors

---

.gitignore
README.md
cmds/clients/contestcli/descriptors/start-literal.json
cmds/clients/contestcli/descriptors/start-literal.yaml

Update README and fix start-literal test descriptor
